const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const mapping = {
  "NOTICE KA KAM LENA": "TAKE NOTICE ASSIGNMENT",
  "NOTICE KA DATA LENA": "COLLECT NOTICE DATA",
  "NOTICE KI LIST TAIYAR KARNA": "PREPARE NOTICE LIST",
  "NOTICE MAIL MARGE /SOFTWARE SE BANANA": "GENERATE NOTICE VIA SOFTWARE/MAIL MERGE",
  "DISPETCH KARWANA": "DISPATCH NOTICES",
  "BILL BANWANA": "PREPARE BILLING",
  "PAYMENT MANGWANA": "REQUEST PAYMENT",
  "RECOVERY SUIT / PSA APPLICATION TAIYAR KARNA": "PREPARE RECOVERY SUIT / PSA APPLICATION",
  "BRANCH SE DOC LENA": "COLLECT DOCUMENTS FROM BRANCH",
  "FILE TAIYAR KARNA": "PREPARE CASE FILE",
  "ADVOCATE KO TAIYAR KARKE SUBMIT KARWANA": "SUBMIT TO ADVOCATE",
  "RODA FILE SCAN": "SCAN RODA FILE",
  "RODA SET": "PREPARE RODA SET",
  "RODA FILE TAIYAR KARNA": "PREPARE RODA FILE",
  "RODA FILE SDM OFFICE MEN LAGANA": "SUBMIT RODA FILE TO SDM OFFICE",
  "SUMMON NIKALWNA": "ISSUE SUMMONS",
  "SARFEASI NOTICE DATA LENA": "COLLECT SARFAESI NOTICE DATA",
  "SARFEASI NOTICE NOTICE BANANA": "DRAFT SARFAESI NOTICE",
  "NOTICE DISPETCH": "DISPATCH NOTICE",
  "POST OFFICE TRACKING NIKALANA": "OBTAIN POST OFFICE TRACKING",
  "SOE TYPING PRINTING": "SOE TYPING & PRINTING",
  "SY. POSSESSION LENA": "TAKE SYMBOLIC POSSESSION",
  "POSSESSTION NOTICE DISPETCH": "DISPATCH POSSESSION NOTICE",
  "NEWS PAPER MEN NIKALWANA": "PUBLISH IN NEWSPAPER",
  "DM APPLICATION TYPING PRINTING": "DM APPLICATION TYPING & PRINTING",
  "DM APPLICATION TAIYAR KARNA": "PREPARE DM APPLICATION",
  "DM APPLICATION DM COURT MEN LAGANA": "SUBMIT APPLICATION IN DM COURT",
  "DM ORDER PRAPT KARNA": "OBTAIN DM ORDER",
  "SP APPLICATION TYPING PRINTING": "SP APPLICATION TYPING & PRINTING",
  "SP APPLICATION LAGANA": "SUBMIT SP APPLICATION",
  "THANE SE ANKALAN REPORT MANGWANA": "OBTAIN ASSESSMENT REPORT FROM POLICE STATION",
  "DD KE LIYE ORDER NIKALWANA": "OBTAIN ORDER FOR DD",
  "SP OFFICE LETTER KE SATH DD JAMA KARWANA": "SUBMIT DD WITH SP OFFICE LETTER",
  "POSSESSTION KE LIYE ORDER NIAKLWANA": "OBTAIN ORDER FOR POSSESSION",
  "POLICE ARRENGMENT KARNA THANA/POLICE LINE": "ARRANGE POLICE ASSISTANCE",
  "PY. POSSESSION LENA": "TAKE PHYSICAL POSSESSION",
  "NOTICE DATA": "COLLECT NOTICE DATA",
  "NOTICE TAIYAR KARNA": "PREPARE NOTICE",
  "TRACKING": "TRACK POSTAL DELIVERY"
};

async function main() {
  let count = 0;
  for (const [oldName, newName] of Object.entries(mapping)) {
    const res = await prisma.legalWorkLog.updateMany({
      where: { subCategory: oldName },
      data: { subCategory: newName }
    });
    count += res.count;
  }
  console.log(`Updated ${count} records.`);
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
