import { DataTypes, Model } from "sequelize";
import sequelize from "../../lib/sequelize";

class LegalRecoveryBill extends Model<any, any> { [key: string]: any; }

LegalRecoveryBill.init({
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  masterId: { type: DataTypes.INTEGER, allowNull: false },
  companyId: { type: DataTypes.STRING, allowNull: false },
  companyCode: { type: DataTypes.STRING, allowNull: false },
  bankId: { type: DataTypes.INTEGER, allowNull: false },
  branchId: { type: DataTypes.INTEGER, allowNull: false },
  invoiceNo: { type: DataTypes.STRING, allowNull: false },
  billDate: { type: DataTypes.DATEONLY, allowNull: false },
  billAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false, defaultValue: 0 },
  paymentReceivedDate: { type: DataTypes.DATEONLY, allowNull: true },
  receivedAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false, defaultValue: 0 },
  tdsAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false, defaultValue: 0 },
  tdsPercent: { type: DataTypes.DECIMAL(7, 3), allowNull: false, defaultValue: 0 },
  dueAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false, defaultValue: 0 },
  updatedById: { type: DataTypes.STRING, allowNull: true },
  updatedByName: { type: DataTypes.STRING, allowNull: true },
  lastModifiedAt: { type: DataTypes.DATE, allowNull: true },
  cancellationReason: { type: DataTypes.TEXT, allowNull: true },
  settlementAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false, defaultValue: 0 },
  settlementReason: { type: DataTypes.TEXT, allowNull: true },
  settledByName: { type: DataTypes.STRING, allowNull: true },
  settledAt: { type: DataTypes.DATE, allowNull: true },
  collectionStatus: { type: DataTypes.STRING, allowNull: true },
  collectionRemark: { type: DataTypes.TEXT, allowNull: true },
  collectionUpdatedById: { type: DataTypes.STRING, allowNull: true },
  collectionUpdatedByName: { type: DataTypes.STRING, allowNull: true },
  collectionUpdatedAt: { type: DataTypes.DATE, allowNull: true },
  remark: { type: DataTypes.TEXT, allowNull: true },
  status: { type: DataTypes.STRING, allowNull: false, defaultValue: "Pending" },
  revenueType: { type: DataTypes.STRING, allowNull: true },
  revenueAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false, defaultValue: 0 },
  internalRemark: { type: DataTypes.TEXT, allowNull: true },
  kabClrHoga: { type: DataTypes.STRING, allowNull: true },
  kyaKrnaPdega: { type: DataTypes.TEXT, allowNull: true },
  category: { type: DataTypes.STRING, allowNull: true },
  priyankaUpdation: { type: DataTypes.TEXT, allowNull: true },
  vishnuUpdation: { type: DataTypes.TEXT, allowNull: true },
  revenueIc: { type: DataTypes.STRING, allowNull: true },
  revenueIcRemark: { type: DataTypes.TEXT, allowNull: true },
  khushal: { type: DataTypes.TEXT, allowNull: true },
  priyankaRemark: { type: DataTypes.TEXT, allowNull: true },
  assignedTo: { type: DataTypes.STRING, allowNull: true },
  importBatchId: { type: DataTypes.STRING, allowNull: true },
}, {
  sequelize,
  tableName: "legal_recovery_bills",
  timestamps: true,
  indexes: [
    { unique: true, name: "uq_legal_bill_company_invoice", fields: ["companyId", "invoiceNo"] },
    { name: "idx_legal_bill_master_status", fields: ["masterId", "status"] },
    { name: "idx_legal_bill_company_due", fields: ["companyId", "dueAmount"] },
  ],
});

export default LegalRecoveryBill;
