import { DataTypes, Model } from "sequelize";
import sequelize from "../../lib/sequelize";

class Vehicle extends Model<any, any> { [key: string]: any; }

Vehicle.init({
  id: { type: DataTypes.STRING, primaryKey: true, allowNull: false },
  registrationNumber: { type: DataTypes.STRING, allowNull: false, unique: true },
  companyId: { type: DataTypes.STRING, allowNull: true },
  companyName: { type: DataTypes.STRING, allowNull: false },
  ownerName: { type: DataTypes.STRING, allowNull: false },
  vehicleName: { type: DataTypes.STRING, allowNull: false },
  vehicleType: { type: DataTypes.STRING, allowNull: false },
  make: { type: DataTypes.STRING, allowNull: false },
  model: { type: DataTypes.STRING, allowNull: false },
  variant: { type: DataTypes.STRING, allowNull: true },
  manufacturingYear: { type: DataTypes.INTEGER, allowNull: true },
  color: { type: DataTypes.STRING, allowNull: true },
  fuelType: { type: DataTypes.STRING, allowNull: true },
  chassisNumber: { type: DataTypes.STRING, allowNull: true },
  engineNumber: { type: DataTypes.STRING, allowNull: true },
  purchaseDate: { type: DataTypes.DATEONLY, allowNull: true },
  purchaseValue: { type: DataTypes.DECIMAL(14, 2), allowNull: true },
  odometer: { type: DataTypes.INTEGER, allowNull: true },
  ownershipType: { type: DataTypes.STRING, allowNull: false, defaultValue: "Company Owned" },
  status: { type: DataTypes.STRING, allowNull: false, defaultValue: "Available" },
  currentAssigneeId: { type: DataTypes.STRING, allowNull: true },
  currentAssigneeName: { type: DataTypes.STRING, allowNull: true },
  currentAssigneeType: { type: DataTypes.ENUM("Employee", "External"), allowNull: true },
  assignedAt: { type: DataTypes.DATE, allowNull: true },
  location: { type: DataTypes.STRING, allowNull: true },
  photoUrl: { type: DataTypes.TEXT, allowNull: true },
  remarks: { type: DataTypes.TEXT, allowNull: true },
  saleDate: { type: DataTypes.DATEONLY, allowNull: true },
  saleAmount: { type: DataTypes.DECIMAL(14, 2), allowNull: true },
  buyerName: { type: DataTypes.STRING, allowNull: true },
  buyerContact: { type: DataTypes.STRING, allowNull: true },
  buyerAddress: { type: DataTypes.STRING, allowNull: true },
  buyerIdProofType: { type: DataTypes.STRING, allowNull: true },
  buyerIdProofTypeOther: { type: DataTypes.STRING, allowNull: true },
  buyerIdProofNumber: { type: DataTypes.STRING, allowNull: true },
  buyerIdProofUrl: { type: DataTypes.TEXT, allowNull: true },
  paymentMode: { type: DataTypes.STRING, allowNull: true },
  paymentModeOther: { type: DataTypes.STRING, allowNull: true },
  paymentReference: { type: DataTypes.STRING, allowNull: true },
  saleOdometer: { type: DataTypes.INTEGER, allowNull: true },
  rtoNocNumber: { type: DataTypes.STRING, allowNull: true },
  saleWitness: { type: DataTypes.STRING, allowNull: true },
  rcTransferStatus: { type: DataTypes.STRING, allowNull: true },
  saleRemarks: { type: DataTypes.TEXT, allowNull: true },
  isInstallmentSale: { type: DataTypes.BOOLEAN, defaultValue: false },
  paymentInstallments: { type: DataTypes.TEXT, allowNull: true },
  handoverDate: { type: DataTypes.DATEONLY, allowNull: true },
  handoverLocation: { type: DataTypes.STRING, allowNull: true },
  handoverBy: { type: DataTypes.STRING, allowNull: true },
  receivedBy: { type: DataTypes.STRING, allowNull: true },
  rcHandedOver: { type: DataTypes.STRING, allowNull: true },
  insuranceHandedOver: { type: DataTypes.STRING, allowNull: true },
  createdById: { type: DataTypes.STRING, allowNull: false },
  createdByName: { type: DataTypes.STRING, allowNull: false },
}, {
  sequelize, tableName: "vehicles", timestamps: true,
  indexes: [
    { fields: ["registrationNumber"], unique: true },
    { fields: ["companyId"] }, { fields: ["status"] }, { fields: ["currentAssigneeId"] },
    { name: "idx_vehicles_company_status", fields: ["companyId", "status"] },
    { name: "idx_vehicles_created_at", fields: ["createdAt"] },
  ],
});

export default Vehicle;
