import sequelize from "./sequelize";
import AuditLog from "../models/sequelize/AuditLog";
import Notification from "../models/sequelize/Notification";
import User from "../models/sequelize/User";
import { sendEmail } from "./email";
import { Op } from "sequelize";

interface AuditParams {
  userId?: string | null;
  action: string;
  entity: string;
  entityId?: string;
  details: string;
  ipAddress?: string;
}

export async function logAudit({
  userId,
  action,
  entity,
  entityId,
  details,
  ipAddress,
}: AuditParams) {
  try {
    await sequelize.authenticate();
    await AuditLog.sync({ alter: true });
    await Notification.sync({ alter: true });
    
    // 1. Save Audit Log (Fully Automated Tracking)
    const audit = new AuditLog({
      id: Date.now().toString() + Math.random().toString(36).substring(2, 7),
      user: userId || null,
      action,
      entity,
      entityId,
      details,
      ipAddress,
    });
    await audit.save();
    console.log(`[AUDIT LOG] ${action} on ${entity} (${entityId || "N/A"})`);

    // 2. Fetch Administrators to notify
    const admins = await User.findAll({
      where: {
        role: {
          [Op.in]: ["Owner", "Director", "HR Head"]
        }
      },
      attributes: ["id", "email"]
    });

    if (admins.length > 0) {
      const adminIds = admins.map((a: any) => a.id);
      const adminEmails = admins.map((a: any) => a.email).filter(Boolean);

      const cleanTitle = action.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      const title = `🔔 ${cleanTitle}`;
      const message = `${details}`;

      // 3. Create In-App Notifications
      const notifications = adminIds.map(adminId => ({
        id: Date.now().toString() + Math.random().toString(36).substring(2, 7),
        recipient: adminId,
        title,
        message,
        read: false,
      }));
      await Notification.bulkCreate(notifications);

      // 4. Send Email Notification
      if (adminEmails.length > 0) {
        // Send asynchronously to avoid blocking the API response
        sendEmail({
          to: adminEmails,
          subject: `RS9 HRMS Alert - ${action}`,
          html: `
            <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #e2e8f0; border-radius: 8px;">
              <h2 style="color: #4f46e5; border-bottom: 2px solid #e0e7ff; padding-bottom: 10px;">RS9 HRMS Automated Alert</h2>
              <p><strong>Action:</strong> ${action}</p>
              <p><strong>Details:</strong> ${details}</p>
              <p><strong>Entity Affected:</strong> ${entity} (ID: ${entityId || "N/A"})</p>
              <p><strong>User Triggered:</strong> ${userId || "System"}</p>
              <p><strong>Timestamp:</strong> ${new Date().toLocaleString()}</p>
              <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
              <p style="font-size: 12px; color: #64748b;">This is a fully automated tracking notification generated by the RS9 HRMS System.</p>
            </div>
          `
        }).catch(err => console.error("Async email failed:", err));
      }
    }
  } catch (error) {
    console.error("Failed to write audit log and notifications:", error);
  }
}
