-- Repair duplicate indexes created by historical request-time sync({ alter: true }) calls.
-- No rows or business data are modified.

ALTER TABLE `bda_leads`
  DROP INDEX `leadId_2`,
  DROP INDEX `leadId_3`,
  DROP INDEX `leadId_4`,
  DROP INDEX `leadId_5`,
  DROP INDEX `leadId_6`,
  DROP INDEX `leadId_7`,
  DROP INDEX `leadId_8`,
  DROP INDEX `leadId_9`,
  DROP INDEX `leadId_10`,
  DROP INDEX `leadId_11`,
  DROP INDEX `leadId_12`,
  DROP INDEX `leadId_13`,
  DROP INDEX `leadId_14`,
  DROP INDEX `leadId_15`,
  DROP INDEX `leadId_16`,
  DROP INDEX `leadId_17`,
  DROP INDEX `leadId_18`,
  DROP INDEX `leadId_19`,
  DROP INDEX `leadId_20`,
  DROP INDEX `leadId_21`,
  DROP INDEX `leadId_22`,
  DROP INDEX `leadId_23`,
  DROP INDEX `leadId_24`,
  DROP INDEX `leadId_25`,
  DROP INDEX `leadId_26`,
  DROP INDEX `leadId_27`,
  DROP INDEX `leadId_28`,
  DROP INDEX `leadId_29`,
  DROP INDEX `leadId_30`,
  DROP INDEX `leadId_31`,
  DROP INDEX `leadId_32`,
  DROP INDEX `leadId_33`,
  DROP INDEX `leadId_34`,
  DROP INDEX `leadId_35`,
  DROP INDEX `leadId_36`,
  DROP INDEX `leadId_37`,
  DROP INDEX `leadId_38`,
  DROP INDEX `leadId_39`,
  DROP INDEX `leadId_40`,
  DROP INDEX `leadId_41`,
  DROP INDEX `leadId_42`,
  DROP INDEX `leadId_43`,
  DROP INDEX `leadId_44`,
  DROP INDEX `leadId_45`,
  DROP INDEX `leadId_46`,
  DROP INDEX `leadId_47`,
  DROP INDEX `leadId_48`,
  DROP INDEX `leadId_49`,
  DROP INDEX `leadId_50`,
  DROP INDEX `leadId_51`,
  DROP INDEX `leadId_52`,
  DROP INDEX `leadId_53`,
  DROP INDEX `leadId_54`,
  DROP INDEX `leadId_55`,
  DROP INDEX `leadId_56`,
  DROP INDEX `leadId_57`,
  DROP INDEX `leadId_58`,
  DROP INDEX `leadId_59`,
  DROP INDEX `leadId_60`,
  ADD INDEX `idx_bda_leads_status_assignee_created` (`status`, `assignedTo`, `createdAt`);

CREATE INDEX `idx_lrf_next_date` ON `legal_recovery_followups` (`nextFollowUpDate`);
CREATE INDEX `idx_lrf_caller_date` ON `legal_recovery_followups` (`callerId`, `callDate`);
CREATE INDEX `idx_lrf_task` ON `legal_recovery_followups` (`taskId`);

