CREATE TABLE IF NOT EXISTS `security_guard_attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `securityId` INT NOT NULL,
  `nbfcId` VARCHAR(255) NULL,
  `nbfcName` VARCHAR(255) NOT NULL,
  `branchId` VARCHAR(255) NULL,
  `branchName` VARCHAR(255) NULL,
  `siteLocation` VARCHAR(255) NULL,
  `guardId` INT NOT NULL,
  `guardName` VARCHAR(255) NOT NULL,
  `guardPhone` VARCHAR(255) NULL,
  `attendanceDate` DATE NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'Present',
  `payableUnits` DECIMAL(4,2) NOT NULL DEFAULT 1,
  `perDayRate` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `payoutAmount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `remarks` TEXT NULL,
  `markedBy` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_security_guard_attendance` (`securityId`, `guardId`, `attendanceDate`),
  KEY `idx_security_guard_attendance_month` (`attendanceDate`)
);
